alias:deny("cancel")
alias:enter("exit", "en", "ex")
alias:items("item", "inv", "inventory", "mm")
alias:email("mail")
alias:savestats("savestat", "saveme")
alias:time("delay")
alias:starterpack("claimsp", "staterpack", "claim")
alias:sellbusiness("sellbiz", "sellbisnis", "selbiz")
alias:clearchat("cc")
alias:givebisnis("givebiz")
alias:mybisnis("mybiz", "business")
